# params.yaml
data_ingestion:
  test_size: 0.20
  random_state: 42

feature_engineering:
  max_features: 1000

model_training:
  C: 10
  max_iter: 1000
  random_state: 42
  penalty: 'l1'
  solver: 'saga'
  class_weight: 'balanced'
